---
# tasks/main.yml (nginxv3)
# Prefix : nginxv3

- name: Install tasks
  import_tasks: install.yml
  when:
    - nginxv3_install_flag | bool
  tags: ["install"]

- name: Configure tasks
  import_tasks: configure.yml
  tags: ["configure"]
