---
# handlers/main.yml (nginxv3)
# Prefix : nginxv3

- name: "Restart nginx"
  systemd:
    name: "nginx.service"
    state: "restarted"
    enabled: yes

- name: "Reload nginx"
  systemd:
    name: "nginx.service"
    state: "reloaded"
    enabled: yes
