---
platforms:
  - name: ${MOLECULE_DISTRO}-${ANSIBLE_VER}
    source:
      alias: ubuntu/${MOLECULE_DISTRO}/amd64

provisioner:
  inventory:
    links:
      group_vars: ${MOLECULE_SCENARIO_DIRECTORY}/group_vars
